// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfpdsdlyublvmxolohhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmcGRzZGx5dWJsdm14b2xvaGhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNDI4ODEsImV4cCI6MjA2NjcxODg4MX0.fRmBxVZamvKhQ5GlsQ3rJAme1x6ZzBRr29Qn8XqKfwo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);